# Generated by Django 5.1.1 on 2024-12-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_options_remove_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('telegram', 'Телеграм')], default='web', max_length=10, verbose_name='Источник заказа'),
        ),
    ]
