# Generated by Django 5.1.3 on 2024-12-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_delivery', '0002_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='is_trend',
        ),
    ]
